### ISSUE TITLE
sheriff 0.16.1 legacy configuration doesn't work

### ISSUE THREAD

**Issue by vnabet** [softarc-consulting/sheriff#114]
Node: 20.12.2
Angular cli: 17.3.8
Sheriff: 0.16.1

steps:
- Create angular 17 projet with cli (default options)
- `npx ng lint` to initialize angular eslint configuration
- `npx ng lint` to execute linting => OK
- `npm i -D @softarc/sheriff-core @softarc/eslint-plugin-sheriff`
- `npx sheriff init`
- adding **legacy** configuration in **.eslintrc.json**
- `npx ng lint` => KO

`An unhandled exception occurred: Failed to load plugin '@softarc/sheriff' declared in '.eslintrc.json#overrides[2]': Cannot find module 'typescript-eslint'`

**Comment by rainerhahnekamp** [comment]
@vnabet, thanks for letting us know. There seems to be an issue with the integration tests. They are there to ensure that exactly these things do not happen.

Let me check first on the tests and then come up with a fix.
