### ISSUE TITLE
Sheriff does not report violations when a barrel file (index.ts) wrongly `export` modules from other places

### ISSUE THREAD

**Issue by hoangvutruong513** [softarc-consulting/sheriff#137]
It seems to me that Sheriff only examines `import` statements and does not really examine `export` statements. This leads to a loophole, for example, where the barrel file in module A can `re-export` dependencies from module B, even if we forbid module A from depending on module B through the `depRules` in `sheriff.config.ts`.

Concrete example below

Assuming below structure:
...
|_ store/index.ts (tagged as `type:store`)
|_ model/index.ts (tagged as `type:model`)

And a simple dependency rule:
```ts
depRules: {
  'type:store': 'type:model'
}
```

In `store/index.ts`:
```ts
export { StoreA } from '...';
export { StoreB } from '...';
```

In `model/index.ts`:
```ts
// This is fine, export from within this `model` module
export { ModelA } from '...'; 
// This is fine, export from within this `model` module
export { ModelB } from '...';
// This is NOT fine. We are reaching into `store` module to re-export its dependencies,
// clearly violating our dependency rules, but Sheriff won't report this as an error, 
export { StoreA, StoreB } from '../store';
// OR even reaching through deep imports, bypassing barrel files, Sheriff still won't
// raise error. Hence my conclusion that Sheriff does not examine `export` statements.
export { StoreA } from '../store/store-a'; // store-a.ts is where StoreA is defined
export { StoreB } from '../store/store-b'; // store-b.ts is where StoreB is defined
```

I suspect this behaviour will be the same if I try to `re-export` dependencies elsewhere in any `.ts` files, not just barrel `index.ts` files. I hope it is possible to fix this loophole.

I was able to detect this using `@softarc/detective` by the way, kudos to @manfredsteyer. Also thank you for this amazing library.

**Comment by rainerhahnekamp** [comment]
Thanks for letting us know. You are right about that.

Has been classified as a bug and hopefully be fixed very soon.
