### ISSUE TITLE
Limit Error Messages

### ISSUE THREAD

**Issue by rainerhahnekamp** [softarc-consulting/sheriff#15]
When there is a basic problem, eslint marks all `import` statements as error. That makes it hard to identify the root cause and is quite confusing.

**Comment by FernandoX66** [comment]
<img width="642" alt="image" src="https://github.com/softarc-consulting/sheriff/assets/75402699/563f110b-6c68-470d-908a-a86f92dbcfcb">

I agree

**Comment by rainerhahnekamp** [comment]
Yup :)

@FernandoX66, you know how to fix this, right? It's "just" an annoyance?

**Comment by rainerhahnekamp** [comment]
Fixed in 0.12.0.
