### ISSUE TITLE
Cannot ignore shared module

### ISSUE THREAD

**Issue by fynnfeldpausch** [softarc-consulting/sheriff#24]
I am trying to gradually introduce sherriff into a large scale project. After finishing the setup I added a single `index.ts` in one module (admin directory) and set up a very simple config with just one module definition:

```
export const sheriffConfig: SheriffConfig = {
  version: 1,
  tagging: {
    'src/app/admin': ['domain:admin']
  },
  depRules: {
    'domain:admin': ['domain:admin']
  }
};
```

My expectation was to only get error messages related to this module. However, a lot of errors are thrown regarding the relation to the Shared module. The Shared module has no index.ts (yet) so I was expecting Sherriff to ignore it. What am I missing or misunderstanding? This makes gradually introducing the tool very hard.

**Comment by rainerhahnekamp** [comment]
Hi, so if your shared folder doesn't have an index.ts, it is considered to be part of the `root` module. You also need to come up with rules for `root`. 

Please take a look at one of the existing example projects: https://github.com/softarc-consulting/sheriff/blob/main/test-projects/angular-iii/sheriff.config.ts

**Comment by fynnfeldpausch** [comment]
Would it be possible to give root access to all modules in order to gradually work with Sherriff module by module and avoid the flood of errors in the beginning. Basically what I am trying to do is start with on simple module and resolve errors in there. Then take the next ones.

By adding an index.ts to the admin modules, I can already fix all deep imports to that very module from the outside. But I don't want to adjust all imports from the shared module (into the admin module) right now.

**Comment by rainerhahnekamp** [comment]
If I understand you correctly, you want to disable the dependency rules at all and only start out with the deep imports?

If yes, then just remove the `sheriff.config.ts`. 

On the other side, if you meant, that module `root` should have access to all other modules, then update your config to this one:

```ts
export const sheriffConfig: SheriffConfig = {
  version: 1,
  tagging: {
    'src/app/admin': ['domain:admin']
  },
  depRules: {
    'root': () => true,
    'domain:admin': ['domain:admin']
  }
};
```

Keep me updated.

**Comment by fynnfeldpausch** [comment]
Sorry, I am quite new to the tool and might not be coming from the right angle. So I have now deleted the `sheriff.config.ts` (didn't know that is possible) to focus on the deep imports first. From the docs, I would expect that only modules with an `index.ts` generate linting errors for deep imports (obviously). I still receive lot's of linting errors related to the shared module (as if Sherriff is treating my shared folder like it had an index.ts, which it does not).
Right now, only the admin module has an index.ts and thus only deep imports to that module should generate errors

**Comment by rainerhahnekamp** [comment]
OK, I think I understand. The `root` module acts as an implicit module. What you want is that it isn't a module at all.

All files from your admin module should be able to import from `root` whatever they want. And if a file of `root` has a dependency on `admin`, it has to be done via the `index.ts`. Right?

Let me think about it. Right now, I think the easiest solution is an option where you can disable the `root` module to simplify the transition.

**Comment by fynnfeldpausch** [comment]
Sounds great. I will also give it some more thoughts and tests in the upcoming days and will call it a day for now.

Many thanks for your immediate help 👏🙏

**Comment by rainerhahnekamp** [comment]
Yup, I think we understand each other. Sheriff defines an artificial module for all your code, which is not behind a barrel file. And that's module `root`. So if you get an option to disable `root`, you have a working solution for your migration.

**Comment by rainerhahnekamp** [comment]
@fynnfeldpausch Would that help?

<img width="841" alt="image" src="https://github.com/softarc-consulting/sheriff/assets/5721205/37e4ab1d-cffb-48e3-b7ed-45a728b14589">

**Comment by fynnfeldpausch** [comment]
That would help a lot

**Comment by rainerhahnekamp** [comment]
This feature is available with the latest version (0.13). Please give it a try and let me know, if that helps you.

**Comment by rainerhahnekamp** [comment]
Oh man, that's quite embarrassing. Lots of tests and I still manage to publish the source code instead the build one. Sorry, will be fixed today.

**Comment by rainerhahnekamp** [comment]
Okay, it is now 0.13.1. That one should work.

@fynnfeldpausch, if you have time and are interested, there is issue #31 about automating the release process. Contributors are always welcome.

**Comment by fynnfeldpausch** [comment]
Cool, will check it out first thing tomorrow.

See https://github.com/softarc-consulting/sheriff/pull/34 for a proposal on #31

**Comment by fynnfeldpausch** [comment]
Works like a charm. Thanks a lot 🥳.

**Comment by rainerhahnekamp** [comment]
Wonderful!
