### ISSUE TITLE
Dependency rule configuration

### ISSUE THREAD

**Issue by Renaldinho** [softarc-consulting/sheriff#46]
I am trying to set up a simple example of sheriff, I've attempted to configure the dependency rules closely to the one provided, and it works, but it works in a way that i can't import common modules like @angular/core with ther error ESLint: Dependency rule (internal error) No assigned Tag for 'a path to a domain module' in sheriff.config.ts

**Comment by Renaldinho** [comment]
Correction: the first import in a file is marked like that. Every one after that follows the rules correctly it seems

**Comment by rainerhahnekamp** [comment]
When you create a `sheriff.config.ts`, all your modules, i.e. directories with an `index.ts` must be tagged. That makes sure you won't skip one. Also make sure that the `paths` in your `tsconfig.json` point to existing files.

If you want just want to use the deep-import checks, remove the `sheriff.config.ts` and it will work.

**Comment by RobinMeow** [comment]
@Renaldinho Maybe this is the cause of your issue: https://github.com/softarc-consulting/sheriff/issues/49

**Comment by rainerhahnekamp** [comment]
Sure, maybe that can help as a starting point: https://github.com/softarc-consulting/sheriff/blob/9850d511610898d2fe32d12e8e59954bea991530/packages/core/src/lib/file-info/traverse-filesystem.spec.ts#L129

All the best!

**Comment by rainerhahnekamp** [comment]
Going to close that since we didn't get any new information and a potential fix was released.
