### ISSUE TITLE
Example for usage with nx monorepo workspace (question)

### ISSUE THREAD

**Issue by richardliebmann** [softarc-consulting/sheriff#48]
Is there any example how to use sheriff with an nx monorepo workspace? I'd like to use it for only one library. Where have I place the config-file and the eslint rule? Currently I only get errors.

Thank's for your help!

**Comment by rainerhahnekamp** [comment]
Hi @richardliebmann , I hope that you could make use of the example. I'm going to close this issue. If there are some further questions, create a new issue. Thanks
