### ISSUE TITLE
hostOrText.readFile is not a function

### ISSUE THREAD

**Issue by ts-script** [softarc-consulting/sheriff#5]
Greetings!

I have a small issue after configuring sheriff.
All my imports are highlighted with the following messages:

**ESLINT: Deep Import (internal error): hostOrText.readFile is not a function (@softarc/sheriff/deep-import)
ESLINT: Dependency Rule (internal error): hostOrText.readFile is not a function (@softarc/sheriff/dependency-rule)**

My sheriff config
`import { noDependencies, sameTag, SheriffConfig } from "@softarc/sheriff-core";

export const config: SheriffConfig = {
  version: 1,
  tagging: {
    'src/app': {
      'shell': 'app:shell',
      '+state': 'app:state',
      'shared': {
        'components': ['shared', 'type:component'],
        'utils': ['shared', 'type:util'],
      },
      'domains/<domain>': {
        'data': ['domain:<domain>', 'type:data'],
        'entities': ['domain:<domain>', 'type:entity'],
        'features/<feature>': {
          presenters: ['domain:<domain>:features:<feature>', 'type:presenter'],
          views: ['domain:<domain>:features:<feature>', 'type:view'],
          skeletons: ['domain:<domain>:features:<feature>', 'type:skeleton'],
        }
      }
    }
  },
  depRules: {
    'root': ['app:shell', 'app:state', 'shared', 'domain:*'],
    'domain:*': [sameTag, 'shared'],
    'shared': 'shared',
    'type:view': ['type:view', 'type:presenter', 'type:entity', 'type:data'],
    'type:presenter': ['type:presenter'],
    'type:data': ['type:entity'],
    'type:entity': noDependencies,
    'type:util': noDependencies,
    'type:component': noDependencies
  }
}
`

eslint file:
`..
    {
      "files": ["*.ts"],
      "extends": ["plugin:@softarc/sheriff/default"]
    }`

Angular Version: 15.2.8

Do you have any idea what should be the problem here?

Thank You in advance

Cheers,
Tom

**Comment by rainerhahnekamp** [comment]
@ts-script fix was released in version 0.0.9. Can you give it try and let me know if it works now?

**Comment by ts-script** [comment]
@rainerhahnekamp Yes, the problem is solved! Thanks for your quick response
