### ISSUE TITLE
Nested path not working

### ISSUE THREAD

**Issue by korneliusz-w** [softarc-consulting/sheriff#55]
Hey

I have problem with defining nested path.

So I have folders strucutre

![image](https://github.com/softarc-consulting/sheriff/assets/4181722/a1e44c24-8d6b-42ac-9a02-ae16244c5dfa)

and sheriff.config

![image](https://github.com/softarc-consulting/sheriff/assets/4181722/e194f76b-6459-4f26-a906-a373e9788f57)

![image](https://github.com/softarc-consulting/sheriff/assets/4181722/c340e31d-a6ec-42cf-9edc-793efcdd17ce)

and still have a lots of errors like:

> C:\front.admin\ClientApp\src\modules\users\ui\ui-change-user-email-modal\ui-change-user-email-modal.component.ts
>   1:1  error  Dependency Rule (internal error): No assigned Tag for 'C:\front.admin\ClientApp\src\modulesusers\ui\ui-change-user-email-modal' in sheriff.config.ts  @softarc/sheriff/dependency-rule

But when I do in this way everythink is ok

> 'src/modules/users/ui/ui-change-user-email-modal': ['domain:users', 'type:ui'],

**Comment by korneliusz-w** [comment]
When I reduced to one single index.ts in each type subfolder it starded to work.
So inside each ui-  subfolder there is no index.ts file

![image](https://github.com/softarc-consulting/sheriff/assets/4181722/58111dd8-f179-49fe-9d34-7e9e1e187c70)
![image](https://github.com/softarc-consulting/sheriff/assets/4181722/5097e551-d982-4f6c-ae31-7f440ff24cd2)

sheriff
![image](https://github.com/softarc-consulting/sheriff/assets/4181722/50c6bd9a-edef-447b-ae62-4ec8c5586141)

**Comment by rainerhahnekamp** [comment]
great to hear. since it is fixed, I'm going to close the issue
