### ISSUE TITLE
Needs a LICENSE.md

### ISSUE THREAD

**Issue by dapperdandev** [softarc-consulting/sheriff#64]
Thank for all of the hard work. This looks great!

What license is this project under? Are you able to add the appropriate LICENSE.md?

**Comment by rainerhahnekamp** [comment]
Hey @dapperdandev , thanks for the info. It will be MIT license. Does that look alright or do I miss anything: https://github.com/softarc-consulting/sheriff/pull/65

**Comment by dapperdandev** [comment]
@rainerhahnekamp lgtm. Thanks again!

**Comment by rainerhahnekamp** [comment]
Thanks for mentioning it!
