### ISSUE TITLE
ignore modules without tags

### ISSUE THREAD

**Issue by fabricio-bastian** [softarc-consulting/sheriff#69]
I'm trying to use Sheriff in an existing angular application, but I can't find a way to do it in an incremental way. 

I tried to follow this https://github.com/softarc-consulting/sheriff?tab=readme-ov-file#5-integrating-sheriff-into-large-project, but since I do have index.ts files in many folders, then Sheriff will complain with something like:
```
 1:1   error    Dependency Rule (internal error): No assigned Tag for 'XXX' in sheriff.config.ts  @softarc/sheriff/dependency-rule
```
where `XXX` is the path to a module.

Maybe I'm doing something wrong, but I don't seem to find a way to circumvent this.
Ideally, what I would like to do is to assign tags to modules gradually and create dependency rules for the modules that are already tagged. But whatever is not tagged, should not be constrained (meaning that is should not be checked).

If there is a way to do that with the latest version, could you please advise me on how I could achieve this?

If this was reported in another rule, it would be possible to turn it off, but since it is the dependency-rule, then it does not really make sense to turn it off or change it to a warning.

**Comment by rainerhahnekamp** [comment]
Dear @fabricio-bastian,

Let me first explain why that is and what you can do about it now and in the future.

In our experience, when many developers are working on a project, modules can be added without proper tagging, which would make them usable by everyone.

Now, with Sheriff, if you do not add a `sheriff.config.ts`, the `index.ts` marks a directory as a module, and you get encapsulation for almost no effort. Dependency Rules are different. There has to be a rule for every module, and we want to keep that the same.

If your application follows conventions, you should be able to set up rules for every module. You can start by tagging all of them with a tag "open" along with dependency rules where every open can access another open.

We also provide you with the `provideRoot` option. You can read more about it here: https://github.com/softarc-consulting/sheriff?tab=readme-ov-file#5-integrating-sheriff-into-large-projects

---

As I understood, you already have an issue with the tagging itself, meaning finding all `index.ts`. We are working towards a CLI that would automatically find all `index.ts` and generate the `sheriff.config.ts` for you.

You must type in the command `npx sheriff init ./src/app/main.ts`, which should do it.

---

Do you think that this will fix your issue?

**Comment by rainerhahnekamp** [comment]
@fabricio-bastian, the new version uses no automatic tagging, so your error no longer exists. I am closing therefore this issue.

**Comment by fabricio-bastian** [comment]
Hi @rainerhahnekamp. Sorry for not getting back to you on this and thank you so much for providing a fix. Looking forward to try out the new version!
