### ISSUE TITLE
Support wildcard libs mapping in tsconfig

### ISSUE THREAD

**Issue by Predhin** [softarc-consulting/sheriff#7]
It looks like the plugin is working only if we have full path provided in the tsconfig --> paths, its not working for wildcard entries like below:
```
    "paths": {
      "@core/*": [
        "./src/app/core/*"
      ]
    } 
```
The path is not getting resolved for the above case. The wilcard entries becomes essential for avoiding multiple nested entries.

**Comment by rainerhahnekamp** [comment]
@Predhin thanks, for letting us know. Expect a fix in the upcoming days

**Comment by Predhin** [comment]
could you please let me know any update on this thread ? thanks.

**Comment by rainerhahnekamp** [comment]
Yes, so (as always) it turned out to be not that easy to fix. Since we are targeting a v1 release soon and this issue has been marked as critical, be assured that it has top priority.

Estimation: This Wednesday or Thursday.

**Comment by rainerhahnekamp** [comment]
Dear @Predhin, wildcard supported landed in the latest version 0.9.0. Please check if it is working and let us know. Thanks

**Comment by Predhin** [comment]
It works!
thanks @rainerhahnekamp for the quick turnaround!

**Comment by rainerhahnekamp** [comment]
Wonderful to hear @Predhin. Thanks for letting us know, and if you come across another issue, don't hesitate to contact us again.
