### ISSUE TITLE
dependency-rule: import from json file cannot be resolved

### ISSUE THREAD

**Issue by attilacsanyi** [softarc-consulting/sheriff#84]
Hi @rainerhahnekamp is there any way to allow importing from `*.json` file?
Sheriff not like this import and seems handle it as typescript file.

```sh
error  import ./my-sample.json cannot be resolved  @softarc/sheriff/dependency-rule
```

`eslint.json``overrides` section:

```json
{
  "files": ["*.ts"],
  "extends": ["plugin:@softarc/sheriff/default"],
  "rules": {
    "@softarc/sheriff/deep-import": "warn",
    "@softarc/sheriff/dependency-rule": "error"
  }
}
```

I try sheriff in a huge repo which has `resolveJsonModule` compile option turned on.

Thanks for any guideline to this.

**Comment by rainerhahnekamp** [comment]
Hi @attilacsanyi, yup that's a feature request and should/will be supported

**Comment by rainerhahnekamp** [comment]
Since my response, we've been working on bringing out the CLI which has now just happened. This issue here is next.
